/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ConversationId = IDL.Text;
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'isRead' : IDL.Bool,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
  'receiver' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationIds' : IDL.Func([], [IDL.Vec(ConversationId)], ['query']),
  'getConversationMessages' : IDL.Func(
      [ConversationId],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getDevDocumentationUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUnreadMessages' : IDL.Func(
      [ConversationId],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessagesAsRead' : IDL.Func([ConversationId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [Message], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const ConversationId = IDL.Text;
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'isRead' : IDL.Bool,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
    'receiver' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationIds' : IDL.Func([], [IDL.Vec(ConversationId)], ['query']),
    'getConversationMessages' : IDL.Func(
        [ConversationId],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getDevDocumentationUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnreadMessages' : IDL.Func(
        [ConversationId],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessagesAsRead' : IDL.Func([ConversationId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [Message], []),
  });
};

export const init = ({ IDL }) => { return []; };